"""Rebuild the synthetic infrastructure fixture without network access."""
import csv
import json
import platform
import sys
from pathlib import Path
import numpy as np
import pydantic
from omicsbench.models import Dataset,Sample
from omicsbench.hashing import digest
from omicsbench.rnaseq import diagnostic,preservation,select_genes

ROOT=Path(__file__).resolve().parents[1]
def write_json(path,obj):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(obj,indent=2,sort_keys=True,allow_nan=False)+'\n',encoding='utf-8')

def write_counts(path,genes,samples,counts):
    path.parent.mkdir(parents=True,exist_ok=True)
    with path.open('w',encoding='utf-8',newline='') as stream:
        writer=csv.writer(stream,delimiter='\t',lineterminator='\n')
        writer.writerow(['gene_id']+samples)
        writer.writerows([g]+[int(x) for x in row] for g,row in zip(genes,counts))

def build(root=ROOT):
    folder=root/'datasets/rnaseq/fixture-001'
    folder.mkdir(parents=True,exist_ok=True)
    config=json.loads((ROOT/'workflows/fixture-config.json').read_text())
    rng=np.random.Generator(np.random.PCG64(config['seed']))
    samples=[Sample(sample_id=f'{c}{i}',condition=c,replicate=i,batch='A' if i<=2 else 'B',strandedness='not_applicable') for c in ['control','treated'] for i in range(1,5)]
    genes=[f'SYN{i:05d}' for i in range(config['genes'])]
    base=rng.lognormal(3,1.4,len(genes))
    effect=np.zeros(len(genes));effect[:300]=1.2;effect[300:550]=-.9
    columns=[]
    for sample in samples:
        mu=base*np.exp(effect*(sample.condition=='treated'))* (1.15 if sample.batch=='B' else 1)
        columns.append(rng.negative_binomial(25,25/(25+mu)))
    counts=np.array(columns).T
    full=diagnostic(counts,samples)
    write_counts(folder/'expected/source-counts.tsv',genes,[s.sample_id for s in samples],counts)
    curve=[];chosen=None
    for size in config['candidate_sizes']:
        indices=select_genes(genes,counts,size,config['seed'])
        subset=[genes[i] for i in indices]
        values=preservation(full,diagnostic(counts[indices],samples),genes,subset,config['top_k'])
        passed=all(values[k]>=v for k,v in config['minimum'].items())
        curve.append({'features':size,'metrics':values,'pass':passed})
        if chosen is None and passed:chosen=indices
    if chosen is None:raise ValueError('No fixture candidate met the frozen thresholds')
    for tier in ['nano','pocket']:
        write_counts(folder/f'{tier}/counts.tsv',[genes[i] for i in chosen],[s.sample_id for s in samples],counts[chosen])
    write_json(folder/'expected/validation.json',{'baseline_counts':'expected/source-counts.tsv','sample_ids':[s.sample_id for s in samples],'shapes':{t:[len(chosen),len(samples)] for t in ['nano','pocket']},'top_k':config['top_k']})
    write_json(folder/'expected/size-fidelity.json',curve)
    write_json(folder/'expected/baseline.json',{'method':'OLS on log2(CPM+1), condition plus batch; diagnostic only','contrast':full['contrast'],'pca':full['pca'].tolist(),'explained_variance':full['explained'].tolist(),'libraries':full['libraries'].tolist(),'sample_ids':[s.sample_id for s in samples]})
    write_json(folder/'provenance/transform.json',{'seed':config['seed'],'generator':'PCG64 negative binomial','parameters':config,'workflow_sha256':digest(Path(__file__)),'versions':{'python':platform.python_version(),'numpy':np.__version__,'pydantic':pydantic.__version__}})
    (folder/'README.md').write_text('# Synthetic RNA infrastructure fixture\n\nEight generated libraries exercise parsing, sample order, feature reduction, batch design and cache integrity. No patient or experimental data are included.\n\nRun `omicsbench validate fixture-001` from the repository root. Both data tiers contain the smallest candidate that passes the diagnostic profile; they deliberately share content. This fixture is smaller than a normal pocket and is excluded from the biological collection count.\n\nThe baseline fits log2(CPM + 1) to condition and batch. It does not calculate differential-expression p-values and is not a DESeq2 substitute. Exact sample order and unchanged integer counts are mandatory. Thresholds and the complete candidate curve are stored under expected.\n\nThe generator and seed are recorded in provenance/transform.json. Cite the software version when reporting a test; do not cite this fixture as a biological study.\n',encoding='utf-8')
    (folder/'LICENSE-DATA.md').write_text('# Fixture data rights\n\nThese numerical arrays are generated by the project workflow. They contain no third-party observations. The generator is provided with the source code; project licensing must be confirmed by the owner before public release. Local testing is the intended use of this development snapshot.\n',encoding='utf-8')
    files=[]
    for path in sorted(folder.rglob('*')):
        if not path.is_file() or path.name=='manifest.json':continue
        relative=path.relative_to(folder).as_posix()
        tier=relative.split('/')[0] if '/' in relative else 'metadata'
        if tier=='provenance':tier='metadata'
        role='raw_counts' if path.name=='counts.tsv' else 'baseline' if path.name=='source-counts.tsv' else 'metrics' if path.name=='validation.json' else 'provenance' if path.suffix=='.json' else 'license' if path.name=='LICENSE-DATA.md' else 'documentation'
        files.append({'path':relative,'tier':tier,'role':role,'media_type':'text/tab-separated-values' if path.suffix=='.tsv' else 'application/json' if path.suffix=='.json' else 'text/markdown','bytes':path.stat().st_size,'sha256':digest(path)})
    manifest={'schema_version':'1.0','id':'fixture-001','title':'Synthetic condition and batch infrastructure fixture','release':'0.1.0.dev0','assay':'bulk_rna_seq','kind':'synthetic_fixture','status':'validated','archetype':'balanced condition and batch','organism':'Synthetic numerical model','taxon_id':None,'source':{'repository':'Project generator','accession':'fixture-001','url':'https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html','citation':'Project-authored numerical fixture, no biological source study.','retrieved':'2026-09-06'},'rights':{'status':'GREEN','license':'Project-authored fixture; public license pending owner decision','evidence':'Generated locally from a recorded seed without third-party observations. GREEN denotes source provenance clearance, not a public license grant.','checked':'2026-09-06'},'reference':{'genome':'none','annotation':'none','namespace':'SYN numerical identifiers','compatibility':'not_applicable'},'samples':[s.model_dump() for s in samples],'derivation':{'workflow':'workflows/build_fixture.py','commit':None,'seed':config['seed'],'algorithm':'mixture-feature-selector-v1','parameters':config,'versions':{'python':platform.python_version(),'numpy':np.__version__,'pydantic':pydantic.__version__}},'files':files,'validation':{'profile':'expected/validation.json','baseline_version':'diagnostic-ols-cpm-v1','metrics':[{'name':k,'minimum':v,'definition':config['definitions'][k]} for k,v in config['minimum'].items()]},'limitations':['Synthetic fixture; excluded from curated biological collection totals.','Diagnostic effects are not inferential differential-expression results.','No reference compatibility or read mapping is demonstrated by this fixture.']}
    manifest['derivation']['parameters']={'genes':config['genes'],'top_k':config['top_k'],'candidate_sizes':config['candidate_sizes']}
    Dataset.model_validate(manifest)
    write_json(folder/'manifest.json',manifest)
    return curve

if __name__=='__main__':
    build(Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT)
