args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) stop("Usage: Rscript deseq2_baseline.R counts.tsv samples.tsv output_directory")
suppressPackageStartupMessages(library(DESeq2))
counts <- as.matrix(read.delim(args[1], row.names = 1, check.names = FALSE))
samples <- read.delim(args[2], row.names = 1, check.names = FALSE)
if (!identical(colnames(counts), rownames(samples))) stop("Sample order differs between counts and design")
if (anyNA(counts) || any(counts < 0) || any(counts != floor(counts))) stop("Counts must be non-negative integers")
if (!all(c("condition", "batch") %in% names(samples))) stop("Design requires condition and batch")
samples$condition <- factor(samples$condition)
samples$batch <- factor(samples$batch)
if (nlevels(samples$condition) != 2 || any(table(samples$condition) < 2)) stop("Two conditions with replication are required")
design_formula <- if (nlevels(samples$batch) > 1) ~ batch + condition else ~ condition
design_matrix <- model.matrix(design_formula, samples)
if (qr(design_matrix)$rank < ncol(design_matrix)) stop("Condition and batch are confounded")
if (nrow(design_matrix) <= ncol(design_matrix)) stop("The design has no residual degrees of freedom")
dds <- DESeqDataSetFromMatrix(counts, samples, design_formula)
dds <- DESeq(dds)
groups <- levels(samples$condition)
result <- results(dds, contrast = c("condition", groups[2], groups[1]), alpha = 0.05)
dir.create(args[3], recursive = TRUE, showWarnings = FALSE)
write.table(as.data.frame(result), file.path(args[3], "differential_expression.tsv"), sep = "\t", quote = FALSE, col.names = NA)
write.table(counts(dds, normalized = TRUE), file.path(args[3], "normalized_counts.tsv"), sep = "\t", quote = FALSE, col.names = NA)
capture.output(sessionInfo(), file = file.path(args[3], "session-info.log"))
writeLines(paste(groups[2], "versus", groups[1]), file.path(args[3], "contrast.log"))
