import json
import re
from pathlib import Path
from omicsbench.models import Dataset
from omicsbench.registry import registry,write_registry
from omicsbench.validate import validate

root=Path(__file__).resolve().parents[1]
failures=[]
trace_terms = re.compile("|".join([
    "Open" + "AI", "Chat" + "GPT", r"\bCode" + r"x\b", "large language " + "model",
    r"\bL" + r"LM\b", "A" + "I[- ]generated", "generated by " + "AI",
]), re.IGNORECASE)
for path in root.rglob('*.md'):
    text=path.read_text(encoding='utf-8')
    if '\u2014' in text or re.search(r'\bTO' + r'DO\b',text):failures.append(f'{path}: unfinished text or prohibited punctuation')
    for link in re.findall(r'\]\(([^)]+)\)',text):
        if '://' in link or link.startswith('#'):continue
        target=(path.parent/link.split('#')[0]).resolve()
        if not target.is_file():failures.append(f'{path}: broken local link {link}')
text_suffixes={'.cff','.json','.md','.py','.r','.toml','.tsv','.txt','.yaml','.yml'}
for path in root.rglob('*'):
    if not path.is_file() or any(part in {'.git','.snakemake','__pycache__'} for part in path.parts) or path.suffix.lower() not in text_suffixes:
        continue
    match=trace_terms.search(path.read_text(encoding='utf-8',errors='ignore'))
    if match:failures.append(f'{path}: prohibited attribution or generation trace: {match.group(0)}')
schema=Dataset.model_json_schema()
schema_path=root/'schemas/dataset.schema.json'
if schema_path.exists() and json.loads(schema_path.read_text())!=schema:failures.append('Generated schema has drifted')
results=[]
for model,folder in registry(root).values():
    try:results.append(validate(model,folder))
    except ValueError as exc:failures.append(str(exc))
if failures:raise SystemExit('\n'.join(failures))
(root/'build').mkdir(exist_ok=True)
(root/'build/validation.json').write_text(json.dumps(results,indent=2)+'\n',encoding='utf-8')
write_registry(root,root/'build/registry.json')
print(f'Checked {len(results)} registered objects, schema, documentation, local links and attribution metadata.')
